name: PR Comment Notification

on:
 issue_comment:
    types: [created]
 pull_request:
    types: [closed]

jobs:
  send-comment-email:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Comment Notification Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Your SMTP server
          server_port: 465                # Port for SMTP
          username: ${{ secrets.EMAIL_USERNAME }}  # GitHub Secrets for sensitive data
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "New Comment on PR #${{ github.event.issue.number }}"
          body: |
            A new comment has been posted on pull request #${{ github.event.issue.number }}.
            
            **Comment by:** ${{ github.event.comment.user.login }}
            **Comment:**
            ${{ github.event.comment.body }}
            
            View it on GitHub: ${{ github.event.comment.html_url }}
          to: vaishnaviaddaguduru@gmail.com
          from: vaishnaviaddaguduru@gmail.com
