name: Send Comment Details on PR Approval

on:
  pull_request_review:
    types: [submitted]  # Trigger on submitted reviews
    # You can add a condition to filter for approvals
    # For example, using `if: github.event.review.state == 'approved'` inside jobs.

jobs:
  send-comment-email:
    if: ${{ github.event.review.state == 'approved' }}  # Only run if the review is approved
    runs-on: ubuntu-latest

    steps:
      - name: Get PR Details
        id: pr_info
        run: |
          # Get the PR details
          PR_NUMBER=${{ github.event.pull_request.number }}
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          BRANCH_OWNER=${{ github.event.pull_request.user.login }}
          
          # Output to GitHub environment variables
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "BRANCH_OWNER=$BRANCH_OWNER" >> $GITHUB_ENV

          # Fetch the comments on the PR
          COMMENTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments)

          # Save the comments to an environment variable
          echo "COMMENTS=$COMMENTS" >> $GITHUB_ENV

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Or your chosen SMTP server
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: vaishnaviaddaguduru@gmail.com  # The recipient of the email
          subject: "PR #${{ env.PR_NUMBER }} Approved (Branch: ${{ env.BRANCH_NAME }}, Owner: ${{ env.BRANCH_OWNER }})"
          body: |
            The pull request #${{ env.PR_NUMBER }} has been approved.

            **Branch Name**: ${{ env.BRANCH_NAME }}
            **Branch Owner**: ${{ env.BRANCH_OWNER }}

            **Comments on the Pull Request**:
            ${{ env.COMMENTS }}

            You can view the pull request here: https://github.com/${{ github.repository }}/pull/${{ env.PR_NUMBER }}

          from: ${{ secrets.EMAIL_USERNAME }}
